# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# == Distribution preparation ==
ARG DIST
FROM $DIST

# Provide /bin/retry
RUN \
  echo -e '#!/bin/bash\n"$@" || { sleep 15 ; "$@" ; } || { sleep 90 ; "$@" ; }' > /bin/retry && chmod +x /bin/retry

# Upgrade packages
RUN retry yum -y upgrade

# Install dependencies
# electron needs libXss.so.1 and libgconf-2.so.4
RUN retry yum -y install \
    findutils file bzip2 \
    gcc-c++ git libtool gettext-devel perl-XML-Parser \
    alsa-lib-devel flac-devel libgnomecanvas-devel libvorbis-devel fluidsynth-devel libmad-devel \
    pandoc doxygen graphviz \
    npm ImageMagick libXScrnSaver GConf2

# Setup build environment and provide the git repositories
COPY ./.git/ /tmp/beast.git
RUN \
  mkdir -p /opt/src/ && \
  cd /opt/src/ && \
  git clone /tmp/beast.git
WORKDIR /opt/src/beast

# Configure source tree, possibly using compiler wrapper
RUN make default prefix=/opt

# Build sources in parallel
RUN nice make -j`nproc`

# Validate Build
RUN make check
RUN make install
RUN make installcheck
RUN make dist
RUN make uninstall

# docker build --build-arg DIST=fedora:27 -f misc/Dockerfile-yum -t beast-fedora-27 .
