# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# == Distribution preparation ==
ARG DIST
FROM $DIST

WORKDIR /usr/src/beast

# make sure getpwuid() works, and ~/ is writable, otherwise many tools break
ARG USERGROUP
RUN : && \
  \
  echo '## Provide g++ >= 8' && \
  retry apt-get update && \
  retry eatmydata apt-get -y install g++-8 && \
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7 && \
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 && \
  \
  mkdir -m 0755 -p /home/cibuilder/.electron/ && \
  groupadd --gid ${USERGROUP#*:} cibuilder && \
  useradd --uid ${USERGROUP%:*} --gid ${USERGROUP#*:} --home-dir /home/cibuilder cibuilder && \
  { ! compgen -G "/root/.electron/*.zip" >/dev/null || \
      cp --reflink=auto --preserve=timestamps /root/.electron/*.zip /home/cibuilder/.electron/ ; } && \
  chown -R ${USERGROUP} /home/cibuilder
# Also copies pre-fetched electron download

COPY .cicache/electron/ /home/cibuilder/.electron/
