# BEAST/BSE - Bedevilled Audio System / Bedevilled Sound Engine
# Copyright (C) 2006 Tim Janik
#
## GNU Lesser General Public License version 2 or any later version.

# declare variables that we might want to use += on.
INCLUDES=
MAINTAINERCLEANFILES=
CLEANFILES=
EXTRA_HEADERS=
GENERATED_EXTRA_DIST=
GENERATED=$(GENERATED_EXTRA_DIST)
EXTRA_DIST=$(GENERATED_EXTRA_DIST)

# assign project wide defaults
AM_CFLAGS = -D_BIRNET_SOURCE_EXTENSIONS
AM_CXXFLAGS = -D_BIRNET_SOURCE_EXTENSIONS
