# BEAST tests/

NOINST_TESTS     =
TESTS_CLEANFILES = $(NOINST_TESTS)
noinst_PROGRAMS += $(NOINST_TESTS)

# == clean-tests ==
clean-tests:
	rm -f $(TESTS_CLEANFILES) tests/*.$(OBJEXT)
clean-local: clean-tests
.PHONY: clean-tests

# == check-tests ==
tests_check_TARGETS =
check-tests: $(tests_check_TARGETS)
check-local: check-tests
.PHONY: check-tests
define tests_foreach_RULE
$(TESTPRG)\ CHECK: $(TESTPRG)
	@echo '  EXEC    ' $(TESTPRG) ; $(TESTPRG)
check-tests: $(TESTPRG)\ CHECK
.PHONY: $(TESTPRG)\ CHECK
endef
$(foreach TESTPRG,$(NOINST_TESTS),$(eval $(call tests_foreach_RULE,$(TESTPRG))))

# == installcheck-tests ==
installcheck-tests:
installcheck-local: installcheck-tests
.PHONY: installcheck-tests

# == suite1 ==
NOINST_TESTS         += tests/suite1
tests_suite1_LDADD    = sfi/libsfi-@MAJOR@.la $(LIBBSE_LIBS)
tests_suite1_CXXFLAGS = $(SFI_CPPFLAGS) $(RAPICORN_CFLAGS)
tests_suite1_SOURCES = \
	tests/suite1-main.cc \
	tests/suite1-randomhash.cc

# == testwavechunk ==
NOINST_TESTS                += tests/testwavechunk
SLOWTESTS                   += tests/testwavechunk
tests_testwavechunk_CXXFLAGS = $(SFI_CPPFLAGS) $(RAPICORN_CFLAGS)
tests_testwavechunk_SOURCES  = \
	tests/testwavechunk.cc
tests_testwavechunk_LDADD    = bse/libbse-@MAJOR@.la $(LIBBSE_LIBS)
