/* TestPlugin - used to test the C++ language binding           -*-mode: c++;-*-
 * Copyright (C) 2003 Stefan Westerfeld <stefan@space.twc.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */
#include <bse/bse.idl>

namespace Namespace {

using namespace Sfi;

// test enum
choice FunkynessType {
  REALLY_FUNKY,
  MODERATELY_FUNKY,
  NON_FUNKY = (42, "No Funk At All"),
};

// test record
record TestRecord {
  Int           i;
  String        str;
  FunkynessType funky;
};

// adds i and str to the record given by rec
// TestRecord record_add (TestRecord rec, Int i, String str);

// test effect
class TestObject : Bse::Effect {
  Info    category  = "/Test/Plugin";
  // required because otherwise the bse-plugin-generator generated thing doesn't compile
  property Int fixme;
};

// test procedure
Int test_exception (Int i, TestObject o, Int bar, FunkynessType ft) {
  Info category = "/Toys/Test Exception";
}

};
