// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
include "bse/bse.idl";
namespace Namespace {
using namespace Sfi;
// test enum
enum FunkynessType {
  REALLY_FUNKY,
  MODERATELY_FUNKY,
  NON_FUNKY = Enum (42, "No Funk At All"),
};
// test record
record TestRecord {
  Int           i;
  String        str;
  FunkynessType funky;
};
sequence TestSequence {
  TestRecord tr;
};
// adds i and str to the record given by rec
// TestRecord record_add (TestRecord rec, Int i, String str);
// test effect
interface TestObject : Bse::Effect {
  Info    category  = "/Test/Plugin";
  // required because otherwise the bse-plugin-generator generated thing doesn't compile
  property Int aninteger;
  property TestRecord r;
  property TestSequence s;
  // deprecated: property BBlock bb;
  // deprecated: property FBlock fb;
  property Rec rr;
  property Bse::Effect ef; // C++ Object 
  property Bse::Item it;   // C Object
};
// test procedure
Int test_exception (Int i, TestObject o, Int bar, FunkynessType ft) {
  Info category = "/Toys/Test Exception";
}
};
