/*   -*-mode: c++;-*- */
namespace Test  // this comment tests C++ style comments
{
/* test string stuff */
Const ANSWER_A = "the answer to all questions";
Const ANSWER_B = 42;
Const ULTIMATE_ANSWER = (ANSWER_A " is " ANSWER_B);

choice YesNoUndecided {
  Undecided = (Neutral, "Undecided"),
        Yes = (1, "Yes"),
         No = (2, "No")
};

record Position {
  Real x = ("X", "", 2.0, -10.0, 10.0, 1, ":readwrite");
  Real y = ("Y", "", 3.0, -10.0, 10.0, 1, ":readwrite");
  YesNoUndecided relevant = ("Relevant", "", "test-yes", ":readwrite");
};

record SickGenericThings {
  // $GROUP = "foo";
  Rec   rec   = ("Rec", "", ":readwrite");
};

class Blub {
  property Real x;
  // property "X-Group" Real y;
  group "Other Properties" {
    Num z;
  };
};

sequence PositionSeq {
  Position positions = ("Position", "", ":readwrite");
};

/* test that C++ style commments are properly ignored within strings */
Const CXX_COMMENT_TEST_1 = "Foo // bar";
Const CXX_COMMENT_TEST_2 = "Foo \" // bar";
Const CXX_COMMENT_TEST_3 = "Foo \\";//bar

};
/* vim:set ts=8 sts=2 sw=2 syntax=cpp: */
