// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
include "bse/bse.idl";
namespace Bse {
interface Balance : Effect {
  Info    icon      = "icons/balance.png";
  Info    authors   = "Tim Janik";
  Info    license   = _("GNU Lesser General Public License");
  Info    category  = _("/Spatial/Balance");
  Info    blurb     = _("BseBalance is a stereo panning module with "
                        "two audio and two control inputs, each of which can "
                        "be seperately level adjusted. "
                        "The resulting output balance is controlled by a balance adjustment "
                        "and the sum of the control inputs. "
                        "To avoid aliasing artefacts for rapid balance changes, the control "
                        "signal is preprocessed by a simple lowpass filter with adjustable "
                        "cutoff frequency.");
  IStream audio_in1  = (_("Audio In1"), _("First audio input"));
  IStream audio_in2  = (_("Audio In2"), _("Second audio input"));
  IStream ctrl_in1   = (_("Ctrl In1"), _("First control input"));
  IStream ctrl_in2   = (_("Ctrl In2"), _("Second control input"));
  OStream left_out   = (_("Left Out"), _("Left audio output"));
  OStream mix_out    = (_("Mix Out"), _("Mixed audio output"));
  OStream right_out  = (_("Right Out"), _("Right audio output"));
  group _("Audio Input") {
    Real  alevel1    = Perc (_("Input 1 [%]"), _("Attenuate the level of audio input 1"), 100, STANDARD);
    Real  alevel2    = Perc (_("Input 2 [%]"), _("Attenuate the level of audio input 2"), 100, STANDARD);
    Real  abalance   = Balance (_("Balance"), _("Balance audio input levels"), 0, GUI);
  };
  group _("Control Input") {
    Real  clevel1    = Perc (_("Input 1 [%]"), _("Attenuate the level of control input 1"), 100, STANDARD);
    Real  clevel2    = Perc (_("Input 2 [%]"), _("Attenuate the level of control input 2"), 100, STANDARD);
    Real  cbalance   = Balance (_("Balance"), _("Balance control input levels"), 0, GUI);
  };
  group _("Output Panning") {
    Real  ostrength  = Perc (_("Control Strength"), _("Adjust how much the control signals affect the output balance"), 100, STANDARD);
    Real  lowpass    = Real (_("Lowpass [Hz]"), _("Lowpass filter frequency for the control signal"), 100, 100, 1000, 10, "scale:" STANDARD);
    Real  obalance   = Balance (_("Output Balance"), _("Adjust output balance between left and right"), 0, STANDARD);
  };
};
};
