// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
#include <bse/bsecxxmodule.idl>
namespace Bse {
class Noise : Effect {
  Info    icon        = "icons/noise.png";
  Info    authors     = "Tim Janik";
  Info    license     = _("GNU Lesser General Public License");
  Info    category    = _("/Audio Sources/Noise");
  Info    blurb       = _("Noise is a generator of (supposedly) white noise");
  OStream noise_out   = (_("Noise Out"), _("Noise Output"));
};
} // Bse
