// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
#include <bse/bse.idl>
namespace Bse {
namespace Dav {
interface BassFilter : Effect {
  Info    icon      = "icons/davbassfilter.png";
  Info    authors   = "David A. Bartold, Tim Janik";
  Info    license   = _("GNU Lesser General Public License");
  Info    category  = _("/Filters/Bass Filter");
  Info    blurb     = _("DavBassFilter is a low-pass resonant TB-303 style filter based "
                        "on the VCF303 portions of gsyn v0.2. The filter algorithm is partly "
                        "based on the one described in \"Musical Applications of Microprocessors\" "
                        "by Hal Chamberlin.");
  IStream audio_in   = (_("Audio In"), _("Audio input"));
  IStream trigger_in = (_("Trigger In"), _("Trigger input"));
  OStream audio_out  = (_("Audio Out"), _("Filtered audio output"));
  group _("Parameters") {
    Real cutoff_perc = Perc (_("Cutoff [%]"), _("Set the cutoff frequency percentage"), 50, STANDARD ":automate:");
    Real reso_perc   = Perc (_("Resonance [%]"), _("Set the amount of resonance in percent"), 99.5, STANDARD ":automate:");
    Real env_mod     = Perc (_("Envelope Modulation [%]"), _("Set the envelope magnitude in percent"), 90, STANDARD ":automate:");
    Real env_decay   = Perc (_("Decay [%]"), _("Set the decay length in percent"), 20, STANDARD ":automate:");
    Bool trigger     = Trigger (_("Trigger filter"), NULL, GUI);
  };
};
} // Dav
} // Bse
/* vim:set ts=8 sw=2 sts=2 syntax=cpp: */
