# BEAST af-tests/ - audio feature tests

AF_TESTS_CLEANFILES =

# == clean-tests ==
af-tests-clean:
	rm -f $(AF_TESTS_CLEANFILES) af-tests/*.$(OBJEXT)
clean-local: af-tests-clean
.PHONY: af-tests-clean

# == af-tests-check ==
af-tests-check:
check-local: af-tests-check
.PHONY: af-tests-check

# == MACROS ==
AF_TESTS_BSE2WAV = $(strip					\
	$(topdir)/bse/bsetool					\
	  $(if $(findstring 1, $(V)),, --quiet)			\
	  render2wav						\
	  --bse-mixing-freq=48000				\
	  --bse-pcm-driver null=nosleep				\
	  --bse-midi-driver null				\
	  --bse-rcfile "/dev/null"				\
	  --bse-override-plugin-globs '$(top_builddir)/plugins/.libs/*.so:$(top_builddir)/plugins/freeverb/.libs/*.so' \
	  --bse-override-sample-path '$(top_srcdir)/af-tests:$(top_srcdir)/library/samples' \
	  --bse-disable-randomization )

VERSIONCMP = $(top_srcdir)/af-tests/versioncmp.sh

# == af-tests/adsrtest ==
af-tests/adsrtest: af-tests/adsrtest.bse af-tests/adsrtest.ref
	$(QWAVCHECK)	# ADSR Test checks the mono channel envelope rendering
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/adsrtest

# == af-tests/adsr-wave-1-test ==
af-tests/adsr-wave-1-test: af-tests/adsr-wave-1-test.bse af-tests/adsr-wave-1-test.ref af-tests/pseudo-saw.bsewave
	$(QWAVCHECK)	# test for play-type=adsr-wave-1
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy --end-time >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/adsr-wave-1-test

# == af-tests/adsr-wave-2-test ==
af-tests/adsr-wave-2-test: af-tests/adsr-wave-2-test.bse af-tests/adsr-wave-2-test.ref af-tests/pseudo-stereo.bsewave
	$(QWAVCHECK)	# test for play-type=adsr-wave-2
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy --end-time >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/adsr-wave-2-test

# == af-tests/artscompressor ==
af-tests/artscompressor: af-tests/artscompressor.bse af-tests/artscompressor.ref
	$(QWAVCHECK)	# test for ArtsCompressor
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
# FIXME: af-tests-check: af-tests/artscompressor

# == af-tests/bseadder ==
af-tests/bseadder: af-tests/bseadder.bse af-tests/bseadder.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/bseadder

# == af-tests/balance ==
af-tests/balance: af-tests/balance.bse af-tests/balance.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/balance

# == af-tests/freak-noise ==
af-tests/freak-noise: af-tests/freak-noise.bse af-tests/freak-noise.ref
	$(QWAVCHECK)	# simple loop
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav --seconds 5
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/freak-noise

# == af-tests/minisong ==
af-tests/minisong: af-tests/minisong.bse af-tests/minisong.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 98.00
	$(Q) rm -f $@.wav $@.tmp
# FIXME: af-tests-check: af-tests/minisong

# == af-tests/organsong ==
af-tests/organsong: af-tests/organsong.bse af-tests/organsong.ref
	$(QWAVCHECK)	# test DavOrgan mono voice module
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 98.00
	$(Q) rm -f $@.wav $@.tmp
# FIXME: af-tests-check: af-tests/organsong

# == af-tests/osc-test ==
af-tests/osc-test: af-tests/osc-test.bse af-tests/osc-test.ref
	$(QWAVCHECK)	# a test for the oscillator
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav --seconds 5
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.90
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/osc-test

# == af-tests/osctranspose1 ==
af-tests/osctranspose1: af-tests/osctranspose1.bse af-tests/osctranspose1.ref
	$(QWAVCHECK)	# checks that oscillator transposing works if the frequency is constant
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/osctranspose1

# == af-tests/osctranspose2 ==
af-tests/osctranspose2: af-tests/osctranspose2.bse af-tests/osctranspose2.ref
	$(QWAVCHECK)	# checks that oscillator transposing works if the frequency is a signal
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/osctranspose2


# == af-tests/partymonster ==
af-tests/partymonster: $(topdir)/library/demo/partymonster.bse af-tests/partymonster.ref
	$(QWAVCHECK)	# Beast demo song
	$(Q) $(AF_TESTS_BSE2WAV) $(topdir)/library/demo/partymonster.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --join-spectrum-slices=10 --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --join-spectrum-slices=10 --avg-energy --end-time >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
slowcheck: af-tests/partymonster
# FIXME: takes too long: af-tests-check: af-tests/partymonster

# == af-tests/plain-wave-1-test ==
af-tests/plain-wave-1-test: af-tests/plain-wave-1-test.bse af-tests/plain-wave-1-test.ref af-tests/pseudo-square-env.bsewave
	$(QWAVCHECK)	# test for play-type=plain-wave-1
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy --end-time >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/plain-wave-1-test

# == af-tests/plain-wave-2-test ==
af-tests/plain-wave-2-test: af-tests/plain-wave-2-test.bse af-tests/plain-wave-2-test.ref af-tests/pseudo-stereo-env.bsewave
	$(QWAVCHECK)	# test for play-type=plain-wave-2
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy --end-time >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/plain-wave-2-test

# == af-tests/simple-loop ==
af-tests/simple-loop: af-tests/simple-loop.bse af-tests/simple-loop.ref
	$(QWAVCHECK)	# another simple loop
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav --seconds 5
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
# FIXME: af-tests-check: af-tests/simple-loop

# == af-tests/soundfont-test ==
af-tests/soundfont-test: af-tests/soundfont-test.bse af-tests/soundfont-test.ref af-tests/minfluid.sf2 af-tests/minfluid.sf2.LICENSE
	$(QWAVCHECK)	# test for soundfont loading & rendering
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy --end-time  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy --end-time >> $@.tmp
	@: # fluidsynth >= 1.1.7 contains a modulator bugfix (FluidSynth/fluidsynth#194), so lower the thresholds for older versions
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold $(shell $(VERSIONCMP) $(FLUID_VERSION) 1.1.7 99.99 99.7)
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/soundfont-test

# == af-tests/sum-diff-test ==
af-tests/sum-diff-test: af-tests/sum-diff-test.bse af-tests/sum-diff-test.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav --seconds 25
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/sum-diff-test

# == af-tests/syndrum ==
af-tests/syndrum: af-tests/syndrum.bse af-tests/syndrum.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 91.00
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/syndrum

# == af-tests/velocity ==
af-tests/velocity: af-tests/velocity.bse af-tests/velocity.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 1 --avg-spectrum --spectrum --avg-energy >> $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.99
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/velocity

# == af-tests/xtalstringssong ==
af-tests/xtalstringssong: af-tests/xtalstringssong.bse af-tests/xtalstringssong.ref
	$(QWAVCHECK)
	$(Q) $(AF_TESTS_BSE2WAV) $@.bse $@.wav
	$(Q) $(BSEFEXTRACT) $@.wav --cut-zeros --channel 0 --avg-spectrum --spectrum --avg-energy  > $@.tmp
	$(Q) $(BSEFCOMPARE) $@.ref $@.tmp --threshold 99.90
	$(Q) rm -f $@.wav $@.tmp
af-tests-check: af-tests/xtalstringssong
