## Generated data (by make Makefile.icons)
icon_list += ampmix.c
icon_list += any.c
icon_list += atan.c
icon_list += noicon.c
icon_list += pipe.c
icon_list += prod.c
icon_list += sine.c
icon_list += speaker.c
icon_list += sub.c
icon_list += sum.c
icon_list += ampmix.xcf
icon_list += atan.xcf
icon_list += noicon.xcf
icon_list += pipe.xcf
icon_list += prod.xcf
icon_list += sine.xcf
icon_list += speaker.xcf
icon_list += sub.xcf
icon_list += sum.xcf
## Generated data ends here
