# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

skins-images-install:   install-skins_images_tapestryDATA
skins-images-uninstall: uninstall-skins_images_tapestryDATA

skins_images_tapestry_DATA = $(strip	\
	skins/images/biogreen.jpg	\
	skins/images/blueimpress.jpg	\
	skins/images/brownforms.jpg	\
	skins/images/moonpaper.png	\
	skins/images/silvervein.png	\
)
skins_images_tapestrydir = $(pkginstalldir)/skins/images
