# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

skins-install:   install-skins_skinDATA   skins-images-install
skins-uninstall: uninstall-skins_skinDATA skins-images-uninstall

skins_skin_DATA = $(strip		\
	skins/biogreen.skin		\
	skins/blueimpress.skin		\
	skins/brownforms.skin		\
	skins/moonpaper.skin		\
	skins/silvervein.skin		\
	skins/white.skin		\
)
skins_skindir = $(pkginstalldir)/skins
