/* BseEvaluator - evaluates expressions               -*-mode: c++;-*-
 * Copyright (C) 2003 Stefan Westerfeld <stefan@space.twc.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * A copy of the GNU Lesser General Public License should ship along
 * with this library; if not, see http://www.gnu.org/copyleft/.
 */
#include <bse/bse.idl>

namespace Bse {

class Evaluator : Bse::Effect {
  /*Info    icon      = "icons/bseevaluator.png";*/
  Info    options   = "unstable";
  Info    authors   = "Stefan Westerfeld";
  Info    license   = _("GNU Lesser General Public License");
  Info    category  = _("/Misc/Evaluator");
  Info    blurb     = _("BseEvaluator is a module which can compute arithmetic operations in a small language. "
                        "The audio input signal is called input, the audio output signal is called output. "
                        "Simple examples for programs would be \"output = input * 5\" or \"output = 2 * input + 1\".");
  IStream input     = (_("Audio In"), _("Audio input"));
  OStream output    = (_("Audio Out"), _("Audio output"));
  group _("Parameters") {
    String source  = String (_("Source code"), _("The source code"), "output = input", STANDARD);
    String status  = String (_("Status"), _("Status used to output error messages"), "", GUI_RDONLY);
  };
};

}; // Bse

/* vim:set ts=8 sw=2 sts=2 syntax=cpp: */
