// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
#include <bse/bsecore.idl>
namespace Bse { interface Effect; }; // FIXME: bad workaround
namespace Bse {
interface BusModule : Effect {
  Info    authors    = "Tim Janik";
  Info    license    = _("GNU Lesser General Public License");
  Info    blurb      = _("Synthesis module used internally by BseBus");
  IStream audio_in1  = (_("Audio In1"), _("First audio input"));
  IStream audio_in2  = (_("Audio In2"), _("Second audio input"));
  OStream audio_out1 = (_("Audio Out1"), _("First audio output"));
  OStream audio_out2 = (_("Audio Out2"), _("Second audio output"));
  group _("Volume") {
    // Real  volume1    = DBVolume (_("Left"), _("Volume adjustment of left channel"), 0, -96, +24, STANDARD);
    // Real  volume2    = DBVolume (_("Right"), _("Volume adjustment of right channel"), 0, -96, +24, STANDARD);
    Real  volume1    = (NULL, NULL, 1, 0, 1000, 10, STANDARD); /* volume factor */
    Real  volume2    = (NULL, NULL, 1, 0, 1000, 10, STANDARD); /* volume factor */
  };
};
};
