// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html

#include <bse/bsecore.idl>
namespace Bse { // FIXME: bad workarounds
class Source;
}

namespace Bse {

class CxxBase : Source {
  // Implementation fully manual
};

} // Bse
