// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
include "bsecxxmodule.idl";
namespace Bse {

record ProbeFeatures {
  Bool          probe_range;
  Bool          probe_energie;
  Bool          probe_samples;
  Bool          probe_fft;
};

record Probe {
  Int           channel_id;
  Num           block_stamp;
  Real          mix_freq;
  ProbeFeatures probe_features;
  Real          min;			// FIXME: rename to range_min
  Real          max;
  Real          energie;
  FloatSeq      sample_data;
  FloatSeq      fft_data;
};
sequence ProbeSeq {
  Probe probes;
};

record ProbeRequest {
  Source        source;
  Int           channel_id;
  Real		frequency;
  ProbeFeatures probe_features;
};
sequence ProbeRequestSeq {
  ProbeRequest probe_requests;
};
void source_request_probes (Source          source,
                            Int             ochannel_id,
                            ProbeFeatures   probe_features);
void source_mass_request   (ProbeRequestSeq prseq);
Num  source_get_tick_stamp (Source          obj);
Int  source_get_mix_freq   (Source          obj);

};
