/* BSE - Bedevilled Sound Engine                        -*-mode: c++;-*-
 * Copyright (C) 2003-2006 Tim Janik
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * A copy of the GNU Lesser General Public License should ship along
 * with this library; if not, see http://www.gnu.org/copyleft/.
 */
#include <bse/bsecxxmodule.idl>

namespace Bse {

record ProbeFeatures {
  Bool          probe_range;
  Bool          probe_energie;
  Bool          probe_samples;
  Bool          probe_fft;
};
record Probe {
  Int           channel_id;
  Num           block_stamp;
  Real          mix_freq;
  ProbeFeatures probe_features;
  Real          min;			// FIXME: rename to range_min
  Real          max;
  Real          energie;
  FBlock        sample_data;
  FBlock        fft_data;
};
sequence ProbeSeq {
  Probe probes;
};

record ProbeRequest {
  Source        source;
  Int           channel_id;
  Real		frequency;
  ProbeFeatures probe_features;
};
sequence ProbeRequestSeq {
  ProbeRequest probe_requests;
};

void source_request_probes (Source          source,
                            Int             ochannel_id,
                            ProbeFeatures   probe_features);
void source_mass_request   (ProbeRequestSeq prseq);
Num  source_get_tick_stamp (Source          obj);
Int  source_get_mix_freq   (Source          obj);

};
