// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html
#ifndef __GXK_H__
#define __GXK_H__
#include <sfi/glib-extra.hh>
#include <gtk/gtk.h>
#include <gxk/glewidgets.h>
#include <gxk/gxkaction.hh>
#include <gxk/gxkassortment.hh>
#include <gxk/gxkauxwidgets.hh>
#include <gxk/gxkcanvas.hh>
#include <gxk/gxkcellrendererpopup.hh>
#include <gxk/gxkdialog.hh>
#include <gxk/gxkradget.hh>
#include <gxk/gxkradgetfactory.hh>
#include <gxk/gxkglobals.hh>
#include <gxk/gxkled.hh>
#include <gxk/gxklistwrapper.hh>
#include <gxk/gxkmenubutton.hh>
#include <gxk/gxknotebook.hh>
#include <gxk/gxkparam.hh>
#include <gxk/gxklogadjustment.hh>
#include <gxk/gxkpolygon.hh>
#include <gxk/gxkracktable.hh>
#include <gxk/gxkrackitem.hh>
#include <gxk/gxkscrollcanvas.hh>
#include <gxk/gxksimplelabel.hh>
#include <gxk/gxkspline.hh>
#include <gxk/gxkstatusbar.hh>
#include <gxk/gxkstock.hh>
#include <gxk/gxktexttools.hh>
#include <gxk/gxkutils.hh>
#endif /* __GXK_H__ */
