# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

Demos-install:     install-Demos_demoDATA
Demos-uninstall: uninstall-Demos_demoDATA

Demos_demo_DATA = $(strip		\
	Demos/partymonster.bse		\
	Demos/stereo-through.bse	\
	Demos/x2-midi-test.bse		\
)
Demos_demodir = $(pkginstalldir)/Demos
