// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html

namespace Bst {
/*
enum Test1 {
  FOO1,
  FOO2,
};
record Test2 {
  Test1 tval;
};
*/
using namespace Sfi;
Const STORAGE = ":r:w:S:";
Const STANDARD = STORAGE "G:";



};
