// Licensed GNU LGPL v2.1 or later: http://www.gnu.org/licenses/lgpl.html

namespace Bst {
/*
enum Test1 {
  FOO1,
  FOO2,
};
record Test2 {
  Test1 tval;
};
*/
using namespace Sfi;
Const STORAGE = ":r:w:S:";
Const STANDARD = STORAGE "G:";


/* pattern editor key bindings */
record KeyBindingItem {
  SfiString key_name   = ("", "", "", STANDARD);
  SfiString func_name  = ("", "", "", STANDARD);
  Real      func_param = ("", "", 0, -1e37, 1e30, 100, STANDARD ":scale");
};
sequence KeyBindingItemSeq {
  KeyBindingItem items;
};

};
