# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

keys-install:   install-keys_keybDATA
keys-uninstall: uninstall-keys_keybDATA

keys_keyb_DATA = $(strip	\
	keys/keyrc.de		\
	keys/keyrc.us		\
)
keys_keybdir = $(pkginstalldir)/keys
