# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

keys-install:   install-keys_installDATA
keys-uninstall: uninstall-keys_installDATA

keys_install_DATA = $(strip	\
	keys/keyrc.de		\
	keys/keyrc.us		\
)
keys_installdir = $(beastdatadir)/keys
